sudo: false
language: node_js
cache:
  directories:
  - node_modules
branches:
  only:
  - master
notifications:
  email: false
node_js:
- "6"
before_install:
- npm i -g npm
before_script:
- npm prune
script:
- npm run test
- npm run coverage:check